### ISSUE TITLE
Example request: add example for social logins using Ionic 2

### ISSUE THREAD

**Issue by jabas06** [backand/ionic2-crud-example#1]
Hi,

It would be nice if you provide and example to implement social logins using Ionic 2. Ionic 2 is getting stable too fast.

Thanks.

**Comment by matdehaast** [comment]
I am currently looking at doing this for my own app and have found out how to do it with the API, which can be seen in [https://github.com/backand/angularbknd-sdk/blob/master/src/services/auth.js](url) . 

Having looked at the code it does not look that complicated. The big issue is that the social login api calls are undocumented within their documentation.

If I get it working I will put an example up.
